open-mic-events/config/routes.rb
Rails.application.routes.draw do
  get 'jokes/index'
  get 'all_events/index'
  resources :entries
  root to: "entries#index"
end

open-mic-events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

open-mic-events/app/models/entry.rb
class Entry < ApplicationRecord
    Obscenity.configure do |config|
        config.blacklist = ["angular", "react"]
    end

    validates :mic_name, :address, :date_of_show, presence: true
    validate :no_profane_text

    def day
        self.date_of_show.strftime("%b %e, %Y")
    end

    def no_profane_text
        if Obscenity.profane?(mic_name)
            errors.add(:mic_name, 'must not have bad words')
        end
    end
end

open-mic-events/app/controllers/all_events_controller.rb
class AllEventsController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

open-mic-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

open-mic-events/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where(:date_of_show => Date.today.beginning_of_day..Date.today.end_of_day)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:mic_name, :address, :date_of_show)
    end
end

open-mic-events/app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    jokeList = ['What do kids play when their mom is using the phone? Bored games.', 'What do you call an ant who fights crime? A vigilANTe!', 'Why are snails slow? Because they’re carrying a house on their back.', 'What’s the smartest insect? A spelling bee!','What does a storm cloud wear under his raincoat? Thunderwear.', 'What is fast, loud and crunchy? A rocket chip.', 'How does the ocean say hi? It waves!', 'What do you call a couple of chimpanzees sharing an Amazon account? PRIME-mates.', 'Why did the teddy bear say no to dessert? Because she was stuffed.', 'Why did the soccer player take so long to eat dinner? Because he thought he couldn’t use his hands.', 'Name the kind of tree you can hold in your hand? A palm tree!', 'What do birds give out on Halloween? Tweets.', 'What has ears but cannot hear? A cornfield.', 'What’s a cat’s favorite dessert? A bowl full of mice-cream.', 'Where did the music teacher leave her keys? In the piano!', 'What did the policeman say to his hungry stomach? “Freeze. You’re under a vest.”', 'What did the left eye say to the right eye? Between us, something smells!', 'What do you call a guy who’s really loud? Mike.', 'Why do birds fly south in the winter? It’s faster than walking!', 'Why did the student eat his homework? Because the teacher told him it was a piece of cake.', 'What social event do spiders love to attend? Webbings.']

    randJokesIndices = []
    randJokes = Set[]

    i = 0
    while i < 8 do
      randJokesIndices.append((0..20).to_a.sample)
      i += 1
    end

    j = 0
    while j < 8 do 
      randJokes.add(jokeList[randJokesIndices[j]])
      j += 1
    end

    @jokes = randJokes
  end
end

open-mic-events/app/helpers/all_events_helper.rb
module AllEventsHelper
end

open-mic-events/app/helpers/application_helper.rb
module ApplicationHelper
end

open-mic-events/app/helpers/entries_helper.rb
module EntriesHelper
end

open-mic-events/app/helpers/jokes_helper.rb
module JokesHelper
end

open-mic-events/app/views/all_events/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-2 has-text-centered">Open Mics for <%= day%></h3>

            <div class="mb-5">
                <% entries.each do |entry| %>
                    <%= link_to entry_path(entry) do %>
                        <div class="card">
                            <div class="card-content has-text-centered">
                                <strong><%= entry.mic_name %></strong>
                                <p><%= entry.address %></p>
                                <p><%= entry.date_of_show.strftime("%B %e, %Y @ %l:%M%p") %></p>
                                <div class="columns is-mobile mt-2">
                                   <div class="column has-text-right">
                                        <%= link_to "Edit", entry_path(entry), class: "button is-info has-text-centered" %>
                                    </div>
                                    <div class="column has-text-left">
                                        <%= button_to "Delete", entry_path(entry), method: :delete, class: "button is-danger is-inline has-text-centered" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        <% end %>
    </div>
    </div>
</div>

open-mic-events/app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <header class="card-header has-background-info-light">
    <p class='card-header-title is-size-4 is-centered'><%= entry.mic_name %></p>
  </header>

  <div class='card-content'>
    <div class='content has-text-centered'>
      <p>
        <span class='has-text-weight-bold'>
          <strong>Address:</strong>
          <%= entry.address %>
        </span>
      </p>

      <p>
        <span class='has-text-weight-bold'>
          <strong>Date of show:</strong>
          <%= entry.date_of_show.strftime("%B %e, %Y @ %l:%M%p") %>
        </span>
      </p>
    </div>
  </div>
</div>

open-mic-events/app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mic_name, class: "label" %>
    <%= form.text_field :mic_name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :address, class: "label" %>
    <%= form.text_field :address, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :date_of_show, class: "label" %>
    <%= form.datetime_field :date_of_show, class: "input" %>
  </div>

  <div>
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

open-mic-events/app/views/entries/edit.html.erb
<div class='columns is-centered mt-4'>
  <div class='column is-half'>
    <h1 class="has-text-centered is-size-3 mb-2">Editing entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

open-mic-events/app/views/entries/index.html.erb
<% content_for :title do %>
  Open Mic Events &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<% end %>

<div class="columns mt-3 is-centered is-flex is-flex-wrap-wrap">
  <% @entries.each do |entry| %>
  <div class="column is-one-third is-centered">
    <div class="card m-auto" style="width: 400px;">
      <%= render entry %>
      <div class='card-footer'>
        <p class='m-auto'>
          <span class='has-text-weight-bold'>
            <%= link_to "Show Event", entry, class: "card-footer-item" %>
          </span>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="columns is-centered mt-6"> 
  <div class="column">
    <%= link_to "All Events", all_events_index_path, class: 'button is-link is-outlined is-centered' %>
  </div>
</div>

open-mic-events/app/views/entries/new.html.erb
<div class='columns is-centered mt-4'>
  <div class='column is-half'>
  <h1 class="has-text-centered is-size-3 mb-2">New entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

open-mic-events/app/views/entries/show.html.erb
<div class='columns is-centered mt-6'>
  <div class='column is-half is-centered'>
    <div class='card'>
      <%= render @entry %>
      <div class="columns is-mobile">
        <div class="column has-text-right">
          <%= link_to "Edit", edit_entry_path(@entry), class: "button is-info has-text-centered" %>
        </div>
        <div class="column has-text-left">
          <%= button_to "Delete", @entry, method: :delete, class: "button is-danger is-inline has-text-centered" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="columns is-centered mt-6"> 
  <div class="column is-half has-text-centered p-0">
    <%= link_to "Need Jokes?", jokes_index_path, class: 'button is-link is-outlined is-centered' %>
  </div>
</div>

open-mic-events/app/views/jokes/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @jokes.each do |joke| %>
            <div class='card m-5 p-2 has-background-info-light has-text-weight-medium'>
                <p class='is-size-4'><%= joke %></p>
            </div>
        <% end %>
    </div>
</div>

open-mic-events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open Mic Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render 'shared/header' %>
  <% if notice.present? %>
    <div class='notification is-link is-light'><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class='notification is-danger is-light'><%= alert %></div>
  <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

open-mic-events/app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: 'navbar-item' do %>
            <span class='has-text-weight-bold is-size-4 m-auto'>Open Mic Events</span>
          <% end %>
        </div>
        <div class="navbar">
          <div class="navbar-end">
            <span class="navbar-item">
                <%= link_to "Create New Entry", new_entry_path, class: "button is-success"  %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Open Mic Events
        <% end %>
      </p>
    </div>
  </div>
</section>